[package]
name = "libp2p-quic"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.40", default-features = false }
async-io = "1.3.1"
bytes = "1.0.1"
fnv = "1.0.7"
futures = "0.3.13"
libp2p = { version = "0.36.0", default-features = false }
parking_lot = "0.11.1"
quinn-proto = { version = "0.7.1", default-features = false }
snow = "0.7.2"
thiserror = "1.0.24"
tracing = "0.1.25"
