[package]
name = "libp2p-quic"
version = "0.5.0"
authors = ["David Craven <david@craven.ch>", "Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "libp2p-quic is a noise based quic implementation for rust-libp2p."
repository = "https://github.com/ipfs-rust/libp2p-quic"
license = "ISC"

[features]
noise = ["quinn-noise"]
tls = ["quinn-proto/tls-rustls", "rcgen", "ring", "rustls", "untrusted", "webpki", "x509-signature", "yasna"]

[dependencies]
anyhow = "1.0.41"
async-global-executor = "2.0.2"
async-io = "1.6.0"
bytes = "1.0.1"
ed25519-dalek = "1.0.1"
fnv = "1.0.7"
futures = "0.3.15"
if-watch = "0.2.2"
libp2p = { version = "0.39.1", default-features = false }
multihash = { version = "0.14.0", default-features = false }
parking_lot = "0.11.1"
quinn-noise = { version = "0.2.1", optional = true }
quinn-proto = { version = "0.7.3", default-features = false }
rand_core = "0.5.1"
rcgen = { version = "0.8.11", optional = true }
ring = { version = "0.16.20", optional = true }
rustls = { version = "0.19.1", optional = true, features = ["dangerous_configuration"] }
thiserror = "1.0.26"
tracing = "0.1.26"
udp-socket = "0.1.5"
untrusted = { version = "0.7.1", optional = true }
webpki = { version = "0.21.4", optional = true, features = ["std"] }
x509-signature = { version = "0.5.0", optional = true, features = ["webpki", "rustls", "std"] }
yasna = { version = "0.4.0", optional = true }

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
async-trait = "0.1.50"
libp2p = { version = "0.39.1", default-features = false, features = ["request-response"] }
log-panics = "2.0.0"
rand = "0.8.4"
tracing-subscriber = "0.2.19"

[profile.release]
debug = true

[[example]]
name = "smoke"

[patch.crates-io]
x509-signature = { path = "../barebones-x509" }
